apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        args:
          - "-c"
          - "config_file=/etc/postgresql.conf"
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD 
            value: postgres
        volumeMounts:
          - name: postgresconfig
            mountPath: /etc/postgresql.conf
            subPath: postgresql.conf
      volumes:
      - name: postgresconfig
        configMap:
          name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
